language: r
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

sudo: required

apt_packages:
  - libv8-dev
  - librsvg2-dev
  - libxml2-dev

after_success:
    - Rscript -e 'covr::codecov()'

